const translations = {
  en: {
    app: { name: 'SimplyAID', tagline: 'First Aid Management' },
    nav: { dashboard: 'Dashboard', incidents: 'Incidents', inventory: 'Inventory', employees: 'Employees', departments: 'Departments', reports: 'Reports', settings: 'Settings', notifications: 'Notifications', logout: 'Logout', scanHistory: 'Scan History', idCards: 'ID Cards', treatments: 'Treatments', prescriptions: 'Prescriptions', expiry: 'Expiry Tracking', compliance: 'Compliance', analytics: 'Safety Analytics' },
    auth: { login: 'Sign In', signup: 'Sign Up', email: 'Email Address', password: 'Password', confirmPassword: 'Confirm Password', name: 'Full Name', forgotPassword: 'Forgot password?', loginBtn: 'Sign In', signupBtn: 'Create Account', welcome: 'Welcome back', subtitle: 'Sign in to your account', signupWelcome: 'Get started', signupSubtitle: 'Create your account to begin', haveAccount: 'Already have an account?', noAccount: "Don't have an account?", passwordMismatch: 'Passwords do not match' },
    dashboard: { title: 'Dashboard', totalIncidents: 'Total Incidents', openCases: 'Open Cases', daysLost: 'Days Lost', compliance: 'Compliance', recentIncidents: 'Recent Incidents', departmentOverview: 'Department Overview', trend: 'Incident Trend', quickActions: 'Quick Actions', reportIncident: 'Report Incident', inspectBox: 'Inspect Box', viewReports: 'View Reports' },
    incidents: { title: 'Incidents', new: 'Report Incident', id: 'Incident ID', date: 'Date & Time', injuredPerson: 'Injured Person', department: 'Department', severity: 'Severity', status: 'Status', type: 'Type', location: 'Location', description: 'Description', treatment: 'Treatment Given', treatedBy: 'Treated By', outcome: 'Outcome', daysLost: 'Days Lost', rootCause: 'Root Cause', correctiveAction: 'Corrective Action', bodyPart: 'Body Part Affected', witnesses: 'Witnesses', minor: 'Minor', moderate: 'Moderate', serious: 'Serious', fatal: 'Fatal', reported: 'Reported', under_investigation: 'Under Investigation', resolved: 'Resolved', closed: 'Closed', injury: 'Injury', illness: 'Illness', near_miss: 'Near Miss', dangerous_occurrence: 'Dangerous Occurrence', form18: 'Form 18', reportable: 'Reportable' },
    inventory: { title: 'First Aid Boxes', boxId: 'Box ID', location: 'Location', classType: 'Class', inCharge: 'In-Charge', lastInspection: 'Last Inspection', nextInspection: 'Next Inspection', status: 'Status', items: 'Items', adequate: 'Adequate', needs_replenishment: 'Needs Replenishment', overdue_inspection: 'Overdue Inspection', inspect: 'Log Inspection', replenish: 'Replenish' },
    employee: { profile: 'Employee Profile', idCard: 'ID Card', downloadQr: 'Download QR', regenerateQr: 'Regenerate QR', downloadCard: 'Download Card', printCard: 'Print Card', viewCard: 'View ID Card', viewProfile: 'View Profile', personalInfo: 'Personal Information', orgInfo: 'Organization Information', safetyInfo: 'Safety Information', emergencyContact: 'Emergency Contact', firstAidInfo: 'First Aid Information', qrInfo: 'QR Information', scanHistory: 'Scan History', lastScan: 'Last Scan', noScans: 'No scans recorded', editProfile: 'Edit Profile', status: { active: 'Active', on_leave: 'On Leave', suspended: 'Suspended', resigned: 'Resigned' } },
    guest: { welcome: 'Welcome, Explorer', subtitle: 'Sign in to unlock all features', authRequired: 'Authentication Required', authMessage: 'Please sign in or create an account to use this feature.', signInBtn: 'Sign In', signUpBtn: 'Create Account', continueExploring: 'Continue Exploring', exploreMode: 'Explore Mode', explorerTag: 'Guest' },
    common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', view: 'View', search: 'Search...', filter: 'Filter', export: 'Export', loading: 'Loading...', noData: 'No data found', confirm: 'Confirm', actions: 'Actions', all: 'All', back: 'Back', next: 'Next', submit: 'Submit', close: 'Close' }
  },
  hi: {
    app: { name: 'SimplyAID', tagline: 'प्राथमिक चिकित्सा प्रबंधन' },
    nav: { dashboard: 'डैशबोर्ड', incidents: 'घटनाएं', inventory: 'इन्वेंटरी', employees: 'कर्मचारी', departments: 'विभाग', reports: 'रिपोर्ट', settings: 'सेटिंग्स', notifications: 'सूचनाएं', logout: 'लॉगआउट', scanHistory: 'स्कैन इतिहास', idCards: 'आईडी कार्ड', treatments: 'उपचार', prescriptions: 'पर्चे', expiry: 'समाप्ति ट्रैकिंग', compliance: 'अनुपालन', analytics: 'सुरक्षा विश्लेषण' },
    auth: { login: 'साइन इन', signup: 'साइन अप', email: 'ईमेल पता', password: 'पासवर्ड', confirmPassword: 'पासवर्ड की पुष्टि', name: 'पूरा नाम', forgotPassword: 'पासवर्ड भूल गए?', loginBtn: 'साइन इन', signupBtn: 'खाता बनाएं', welcome: 'वापसी पर स्वागत', subtitle: 'अपने खाते में साइन इन करें', signupWelcome: 'शुरू करें', signupSubtitle: 'शुरू करने के लिए अपना खाता बनाएं', haveAccount: 'पहले से खाता है?', noAccount: 'खाता नहीं है?', passwordMismatch: 'पासवर्ड मेल नहीं खाते' },
    dashboard: { title: 'डैशबोर्ड', totalIncidents: 'कुल घटनाएं', openCases: 'खुले मामले', daysLost: 'खोए दिन', compliance: 'अनुपालन', recentIncidents: 'हाल की घटनाएं', departmentOverview: 'विभाग अवलोकन', trend: 'घटना प्रवृत्ति', quickActions: 'त्वरित कार्य', reportIncident: 'घटना रिपोर्ट', inspectBox: 'बॉक्स निरीक्षण', viewReports: 'रिपोर्ट देखें' },
    incidents: { title: 'घटनाएं', new: 'घटना रिपोर्ट करें', id: 'घटना ID', date: 'दिनांक और समय', injuredPerson: 'घायल व्यक्ति', department: 'विभाग', severity: 'गंभीरता', status: 'स्थिति', type: 'प्रकार', location: 'स्थान', description: 'विवरण', treatment: 'दिया गया उपचार', treatedBy: 'उपचारकर्ता', outcome: 'परिणाम', daysLost: 'खोए दिन', rootCause: 'मूल कारण', correctiveAction: 'सुधारात्मक कार्रवाई', bodyPart: 'प्रभावित शरीर भाग', witnesses: 'गवाह', minor: 'मामूली', moderate: 'मध्यम', serious: 'गंभीर', fatal: 'घातक', reported: 'रिपोर्ट', under_investigation: 'जांच में', resolved: 'हल', closed: 'बंद', injury: 'चोट', illness: 'बीमारी', near_miss: 'निकट चूक', dangerous_occurrence: 'खतरनाक घटना', form18: 'फॉर्म 18', reportable: 'रिपोर्ट योग्य' },
    inventory: { title: 'प्राथमिक चिकित्सा बॉक्स', boxId: 'बॉक्स ID', location: 'स्थान', classType: 'वर्ग', inCharge: 'प्रभारी', lastInspection: 'अंतिम निरीक्षण', nextInspection: 'अगला निरीक्षण', status: 'स्थिति', items: 'सामान', adequate: 'पर्याप्त', needs_replenishment: 'पुनःपूर्ति आवश्यक', overdue_inspection: 'निरीक्षण अतिदेय', inspect: 'निरीक्षण दर्ज करें', replenish: 'पुनःपूर्ति' },
    employee: { profile: 'कर्मचारी प्रोफ़ाइल', idCard: 'आईडी कार्ड', downloadQr: 'QR डाउनलोड', regenerateQr: 'QR पुनर्जनन', downloadCard: 'कार्ड डाउनलोड', printCard: 'कार्ड प्रिंट', viewCard: 'आईडी कार्ड देखें', viewProfile: 'प्रोफ़ाइल देखें', personalInfo: 'व्यक्तिगत जानकारी', orgInfo: 'संगठन जानकारी', safetyInfo: 'सुरक्षा जानकारी', emergencyContact: 'आपातकालीन संपर्क', firstAidInfo: 'प्राथमिक चिकित्सा जानकारी', qrInfo: 'QR जानकारी', scanHistory: 'स्कैन इतिहास', lastScan: 'अंतिम स्कैन', noScans: 'कोई स्कैन दर्ज नहीं', editProfile: 'प्रोफ़ाइल संपादित करें', status: { active: 'सक्रिय', on_leave: 'छुट्टी पर', suspended: 'निलंबित', resigned: 'त्यागपत्र' } },
    guest: { welcome: 'स्वागत है, अन्वेषक', subtitle: 'सभी सुविधाओं को अनलॉक करने के लिए साइन इन करें', authRequired: 'प्रमाणीकरण आवश्यक', authMessage: 'कृपया इस सुविधा का उपयोग करने के लिए साइन इन करें या खाता बनाएं।', signInBtn: 'साइन इन', signUpBtn: 'खाता बनाएं', continueExploring: 'अन्वेषण जारी रखें', exploreMode: 'अन्वेषण मोड', explorerTag: 'अतिथि' },
    common: { save: 'सहेजें', cancel: 'रद्द करें', delete: 'हटाएं', edit: 'संपादित', view: 'देखें', search: 'खोजें...', filter: 'फ़िल्टर', export: 'निर्यात', loading: 'लोड हो रहा है...', noData: 'कोई डेटा नहीं', confirm: 'पुष्टि करें', actions: 'कार्रवाई', all: 'सभी', back: 'पीछे', next: 'अगला', submit: 'जमा करें', close: 'बंद करें' }
  }
};

export default translations;
