const translations = {
  en: {
    app: { name: 'SimplyAID', tagline: 'First Aid Management' },
    nav: { dashboard: 'Dashboard', incidents: 'Incidents', inventory: 'Inventory', employees: 'Employees', departments: 'Departments', reports: 'Reports', settings: 'Settings', notifications: 'Notifications', logout: 'Logout' },
    auth: { login: 'Sign In', email: 'Email Address', password: 'Password', forgotPassword: 'Forgot password?', loginBtn: 'Sign In', welcome: 'Welcome back', subtitle: 'Sign in to your account' },
    dashboard: { title: 'Dashboard', totalIncidents: 'Total Incidents', openCases: 'Open Cases', daysLost: 'Days Lost', compliance: 'Compliance', recentIncidents: 'Recent Incidents', departmentOverview: 'Department Overview', trend: 'Incident Trend', quickActions: 'Quick Actions', reportIncident: 'Report Incident', inspectBox: 'Inspect Box', viewReports: 'View Reports' },
    incidents: { title: 'Incidents', new: 'Report Incident', id: 'Incident ID', date: 'Date & Time', injuredPerson: 'Injured Person', department: 'Department', severity: 'Severity', status: 'Status', type: 'Type', location: 'Location', description: 'Description', treatment: 'Treatment Given', treatedBy: 'Treated By', outcome: 'Outcome', daysLost: 'Days Lost', rootCause: 'Root Cause', correctiveAction: 'Corrective Action', bodyPart: 'Body Part Affected', witnesses: 'Witnesses', minor: 'Minor', moderate: 'Moderate', serious: 'Serious', fatal: 'Fatal', reported: 'Reported', under_investigation: 'Under Investigation', resolved: 'Resolved', closed: 'Closed', injury: 'Injury', illness: 'Illness', near_miss: 'Near Miss', dangerous_occurrence: 'Dangerous Occurrence', form18: 'Form 18', reportable: 'Reportable' },
    inventory: { title: 'First Aid Boxes', boxId: 'Box ID', location: 'Location', classType: 'Class', inCharge: 'In-Charge', lastInspection: 'Last Inspection', nextInspection: 'Next Inspection', status: 'Status', items: 'Items', adequate: 'Adequate', needs_replenishment: 'Needs Replenishment', overdue_inspection: 'Overdue Inspection', inspect: 'Log Inspection', replenish: 'Replenish' },
    common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', edit: 'Edit', view: 'View', search: 'Search...', filter: 'Filter', export: 'Export', loading: 'Loading...', noData: 'No data found', confirm: 'Confirm', actions: 'Actions', all: 'All', back: 'Back', next: 'Next', submit: 'Submit', close: 'Close' }
  },
  hi: {
    app: { name: 'SimplyAID', tagline: 'प्राथमिक चिकित्सा प्रबंधन' },
    nav: { dashboard: 'डैशबोर्ड', incidents: 'घटनाएं', inventory: 'इन्वेंटरी', employees: 'कर्मचारी', departments: 'विभाग', reports: 'रिपोर्ट', settings: 'सेटिंग्स', notifications: 'सूचनाएं', logout: 'लॉगआउट' },
    auth: { login: 'साइन इन', email: 'ईमेल पता', password: 'पासवर्ड', forgotPassword: 'पासवर्ड भूल गए?', loginBtn: 'साइन इन', welcome: 'वापसी पर स्वागत', subtitle: 'अपने खाते में साइन इन करें' },
    dashboard: { title: 'डैशबोर्ड', totalIncidents: 'कुल घटनाएं', openCases: 'खुले मामले', daysLost: 'खोए दिन', compliance: 'अनुपालन', recentIncidents: 'हाल की घटनाएं', departmentOverview: 'विभाग अवलोकन', trend: 'घटना प्रवृत्ति', quickActions: 'त्वरित कार्य', reportIncident: 'घटना रिपोर्ट', inspectBox: 'बॉक्स निरीक्षण', viewReports: 'रिपोर्ट देखें' },
    incidents: { title: 'घटनाएं', new: 'घटना रिपोर्ट करें', id: 'घटना ID', date: 'दिनांक और समय', injuredPerson: 'घायल व्यक्ति', department: 'विभाग', severity: 'गंभीरता', status: 'स्थिति', type: 'प्रकार', location: 'स्थान', description: 'विवरण', treatment: 'दिया गया उपचार', treatedBy: 'उपचारकर्ता', outcome: 'परिणाम', daysLost: 'खोए दिन', rootCause: 'मूल कारण', correctiveAction: 'सुधारात्मक कार्रवाई', bodyPart: 'प्रभावित शरीर भाग', witnesses: 'गवाह', minor: 'मामूली', moderate: 'मध्यम', serious: 'गंभीर', fatal: 'घातक', reported: 'रिपोर्ट', under_investigation: 'जांच में', resolved: 'हल', closed: 'बंद', injury: 'चोट', illness: 'बीमारी', near_miss: 'निकट चूक', dangerous_occurrence: 'खतरनाक घटना', form18: 'फॉर्म 18', reportable: 'रिपोर्ट योग्य' },
    inventory: { title: 'प्राथमिक चिकित्सा बॉक्स', boxId: 'बॉक्स ID', location: 'स्थान', classType: 'वर्ग', inCharge: 'प्रभारी', lastInspection: 'अंतिम निरीक्षण', nextInspection: 'अगला निरीक्षण', status: 'स्थिति', items: 'सामान', adequate: 'पर्याप्त', needs_replenishment: 'पुनःपूर्ति आवश्यक', overdue_inspection: 'निरीक्षण अतिदेय', inspect: 'निरीक्षण दर्ज करें', replenish: 'पुनःपूर्ति' },
    common: { save: 'सहेजें', cancel: 'रद्द करें', delete: 'हटाएं', edit: 'संपादित', view: 'देखें', search: 'खोजें...', filter: 'फ़िल्टर', export: 'निर्यात', loading: 'लोड हो रहा है...', noData: 'कोई डेटा नहीं', confirm: 'पुष्टि करें', actions: 'कार्रवाई', all: 'सभी', back: 'पीछे', next: 'अगला', submit: 'जमा करें', close: 'बंद करें' }
  }
};

export default translations;
